### ISSUE TITLE
Section 2.1.1 Suggested Edits

### ISSUE THREAD

**Issue by rajesh06** [OpenActTexts/Loss-Data-Analytics#2]
**Basic Terminology**
suggest 'cost of of the insured event' rather than 'amount suffered by the insured'

suggest 'how frequently events occurs within a policy period' at the end of the sentence starting 'Here, we focus ...' ("how frequently an event occurs" sounds like a rate; "how frequently events occurs within a policy period" sounds like counts)

**The Importance of Frequency**
suggest rewriting the end of the first paragraph as a numbered list

Second paragraph, first sentence: Do you want "expected" before severity?

**Why Examine Frequency Information**
In the first bullet under Behavioral, it seems like there is a word missing after "personal"
"Databases" doesn't seem like a "motivation" which is the intro for the bulleted list

**Comment by larryleihua** [comment]
"amount suffered by the insured" sounds even better to me. But anyway, you might be right. I tend to close the issue for the above reason. 

I don't think the non-numbered list is an issue.

I think here "frequency times severity" is treated as a whole, so no problem.

I don't think the "Databases" issue is a big issue here.

Sorry that if you don't agree with me, but you can submit new issues if you insist on some issues. I tend to close as many issues as possible to save the time of others who might be interested in reading the issues.

Thx!

**Comment by rajesh06** [comment]
No issues. 
I am not the author so you should feel free to accept or not accept my suggestions at your discretion.
