### ISSUE TITLE
Section 2.2.1 Suggested Edits

### ISSUE THREAD

**Issue by rajesh06** [OpenActTexts/Loss-Data-Analytics#3]
Paragraph preceding equation 2.2 should end F_N() is defined as follows: (or "defined below." if you want to end with a "." rather than a ":") 

Paragraph following equation 2.3: I think you missed the shift key after "moments" ("8" should be "*" to render bold text)

last paragraph on page:
The end of the paragraph needs to be rewritten / re-punctuated.

**Comment by larryleihua** [comment]
Sorry I could not locate the issues mentioned around Eq 2.2 and 2.3. Could you please rephrase your issue based on the following draft book:
https://openacttexts.github.io/Loss-Data-Analytics/C-Frequency-Modeling.html

Thx!
