### ISSUE TITLE
Section 2.2.2 Suggested Editrs

### ISSUE THREAD

**Issue by rajesh06** [OpenActTexts/Loss-Data-Analytics#4]
Second paragraph, first sentence: remove "while"

Second paragraph, last sentence: Should "Billingsley, 2008" be in parenthesizes?

Second paragraph, last sentence: it's not initially clear (at first read) what "its" refers to in this sentence and may tend to cause more confusion. Suggest removing or changing to "and provides the intuition for the moment generating function descriptor.

In Theorem 2.2, need to define pmf prior to the use of the acronym on first use.

**Comment by larryleihua** [comment]
pmf has been defined before already, and the other issues are solved.

**Comment by larryleihua** [comment]
Solved.
